name: The Argo Project
favicon: null
layout_spectrum: 0.5093
typography_spectrum: 0
title: The Argo Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#593a2c'
    - '#617894'
    - '#c10000'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
