name: The Argo Project
favicon: null
layout_spectrum: 0.24605
typography_spectrum: 0.3698748212773353
title: The Argo Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c00000'
    - '#bd9c84'
    - '#5a3a29'
  brandStrength: 0.9124334664084017
  lightness: 0.933042210759595
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
